services:
  - type: web
    name: mdbs
    env: node
    region: ohio
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.19.0
    autoDeploy: true
    plan: starter
    healthCheckPath: /
    numInstances: 1 